### ISSUE TITLE
Dependency issues, and fatal errors.

### ISSUE THREAD

**Issue by levizoesch** [adonisjs/pkg-starter-kit#3]
### Package version

entire repo

### Describe the bug

npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported

added 1003 packages, and audited 1004 packages in 38s

310 packages are looking for funding
  run `npm fund` for details

3 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

---

Pull, install,  run npm audit fix --force

Package dependencies need to be updated, and issues resolved in repo.

**Comment by Julien-R44** [comment]
Please read [npm audit: Broken by Design](https://overreacted.io/npm-audit-broken-by-design)

**Comment by levizoesch** [comment]
Well that is a bummer, I spent several hours trying various repos and your starter projects all meeting same result thinking there was a issue with the specific repo.
